cc_test(
    name = "simple",
    srcs = ["simple.cpp"],
    deps = [
        "//solver/algorithm:A",
        "//solver/algorithm:Z",
        "//solver/builder:simple",
        "@gtest//:gtest_main",
    ],
)
