cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//solver/algorithm:A",
        "//solver/algorithm:Z",
        "//solver/builder:dimacs",
        "//solver/builder:simple",
    ],
)
