cc_binary(
    name = "repl",
    srcs = [
        "context.cpp",
        "context.h",
        "expr.cpp",
        "expr.h",
        "expr_copy.cpp",
        "expr_eval.cpp",
        "expr_tostring.cpp",
        "repl.cpp",
        "token.cpp",
        "token.h",
        "trie.h",
    ],
    linkopts = ["-lncursesw"],
)
