package(default_visibility = ["//visibility:public"])

cc_library(
    name = "builder",
    srcs = [
        "cardinality.cpp",
        "circuit.cpp",
        "coloring.cpp",
        "dimacs.cpp",
        "factor.cpp",
        "langford.cpp",
        "mutilated_chessboard.cpp",
        "partial_order.cpp",
        "pigeonhole.cpp",
        "rand.cpp",
        "simple.cpp",
        "waerden.cpp",
    ],
    hdrs = [
        "builder.h",
        "cardinality.h",
        "circuit.h",
        "coloring.h",
        "dimacs.h",
        "factor.h",
        "langford.h",
        "mutilated_chessboard.h",
        "partial_order.h",
        "pigeonhole.h",
        "rand.h",
        "simple.h",
        "waerden.h",
    ],
    deps = [
        "//solver",
        "//util",
    ],
)
