package(default_visibility = ["//visibility:public"])

cc_library(
    name = "simple",
    srcs = ["simple.cpp"],
    hdrs = ["simple.h"],
    deps = ["//solver"],
)

cc_library(
    name = "dimacs",
    srcs = ["dimacs.cpp"],
    hdrs = ["dimacs.h"],
    deps = ["//solver"],
)
