package(default_visibility = ["//visibility:public"])

cc_library(
    name = "transform",
    srcs = [
        "monotonic.cpp",
        "sat3.cpp",
    ],
    hdrs = [
        "monotonic.h",
        "sat3.h",
    ],
    deps = [
        "//solver",
        "//solver/builder",
        "//util",
    ],
)
