cc_binary(
    name = "factor",
    srcs = ["factor.cpp"],
    deps = [
        "//solver/algorithm",
        "//solver/encoder",
        "//util",
    ],
)

cc_binary(
    name = "life",
    srcs = ["life.cpp"],
    deps = [
        "//solver/algorithm",
        "//solver/encoder",
        "//util",
    ],
)

cc_binary(
    name = "sudoku",
    srcs = ["sudoku.cpp"],
    deps = [
        "//solver/algorithm",
        "//solver/encoder",
        "//util",
    ],
)
